pipeline {
    agent any

    stages {
        stage('Launch') {
            steps {
                sh 'docker run -d -p 8090:8080 --name flask-python-app flask-python-application'
            }
        }
        
    
        
        stage('Container status'){
            steps{
                sh './status.sh'
            }
        }
        
}
