pipeline {
    agent any
    stages {
        stage ('remove') {
            steps {
                sh 'chmod +x ./remove.sh'
                sh './remove.sh'
            }    
        }   
    } 
}
