pipeline {
    agent any

    stages {
        stage('launch') {
            steps {
                sh 'docker run -d -p 8282:8282 --name flask-python-app flask-python-application'
            }
        }
        
    
        
        stage('status'){
            steps{
                sh './status.sh'
            }
        }
    }
}
