pipeline {
    agent any

    stages {
        stage('launch') {
            steps {
                sh 'docker run -d -p 8282:8282 --name flask-python-app flask-python-application'
            }
        }
    }
    post {
        success {
            sh './status.sh'
            
        }
    }
}
