pipeline {
    agent any

    stages {
        stage('docker login') {
            steps {
                sh 'docker login'
            }
        }
    }

    stages {
        stage ('launch') {
            steps {
                sh 'docker run -d -p 8282:8282 --name flask-python-app flask-python-application'
            }
        }
    }
    post {
        success {
            sh 'chmod +x status.sh'
            sh './status_container.sh'
            
        }
    }
}
