pipeline {
    agent any
    stages {
        stage ('git'){
            steps {
                git branch: 'main', url: 'https://github.com/ludicsa/pipeline-jenkins.git'
            }   
        }

        stage ('build') {
            steps {
                sh 'docker build -t flask-python-application .'
            }
        }
    }
    post {
        success {
            sh 'chmod +x status_image.sh'
            sh './status_image.sh'
        }
    }
}
